version: "3"

tasks:
  run:
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml
  migrate:
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  test-migrate:
    cmd:
      go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test